CREATE DATABASE CLINICA_DENTAL_MDO

USE CLINICA_DENTAL_MDO

CREATE TABLE PACIENTES
(
	IDPACIENTE INT PRIMARY KEY IDENTITY(1,1),
	NOMBREPACIENTE NVARCHAR(100),
	CEDULA NVARCHAR(11) UNIQUE,
	TELEFONOPACIENTE NVARCHAR(15)
)

CREATE TABLE DENTISTAS
(
	IDDENTISTA INT PRIMARY KEY IDENTITY(1,1),
	NOMBREDENTISTA NVARCHAR(100),
	TELEFONODENTISTA NVARCHAR(15),
	CORREODENTISTA NVARCHAR(100)
)

CREATE TABLE MOTIVOS
(
	IDMOTIVO INT PRIMARY KEY IDENTITY(1,1),
	DESCRIPCIONMOTIVO NVARCHAR(300)
)

CREATE TABLE CITAS
(
	IDCITA INT PRIMARY KEY IDENTITY(1,1),
	IDPACIENTE INT FOREIGN KEY REFERENCES PACIENTES(IDPACIENTE),
	FECHA DATE,
	HORA TIME,
	DURACION INT, --MINUTOS
	IDDENTISTA INT FOREIGN KEY REFERENCES DENTISTAS(IDDENTISTA),
	IDMOTIVO INT FOREIGN KEY REFERENCES MOTIVOS(IDMOTIVO),
	RESTANTE AS DATEDIFF(DAY, GETDATE(), FECHA),
	ESTADO AS CASE WHEN GETDATE() < CAST(FECHA AS DATETIME) + CAST(HORA AS DATETIME) THEN 'VIGENTE'
					WHEN GETDATE() BETWEEN CAST (FECHA AS DATETIME) + CAST(HORA AS DATETIME) AND DATEADD(MINUTE, DURACION, CAST(FECHA AS DATETIME) + CAST(HORA AS DATETIME))
					THEN 'EN PROCESO'
					ELSE 'FINALIZADO'
					END
)

select * from MOTIVOS