// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoFinal_LP3__Daylin_.Models;

#nullable disable

namespace ProyectoFinal_LP3__Daylin_.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251019021746_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoFinal_LP3__Daylin_.Models.CitaViewModel", b =>
                {
                    b.Property<int>("idCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDCITA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idCita"));

                    b.Property<int>("duracionCita")
                        .HasColumnType("int")
                        .HasColumnName("DURACION");

                    b.Property<DateTime>("fechaCita")
                        .HasColumnType("datetime2")
                        .HasColumnName("FECHA");

                    b.Property<TimeSpan>("horaCita")
                        .HasColumnType("time")
                        .HasColumnName("HORA");

                    b.Property<int>("idDentista")
                        .HasColumnType("int")
                        .HasColumnName("IDDENTISTA");

                    b.Property<int>("idMotivo")
                        .HasColumnType("int")
                        .HasColumnName("IDMOTIVO");

                    b.Property<int>("idPaciente")
                        .HasColumnType("int")
                        .HasColumnName("IDPACIENTE");

                    b.HasKey("idCita");

                    b.HasIndex("idDentista");

                    b.HasIndex("idMotivo");

                    b.HasIndex("idPaciente");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("ProyectoFinal_LP3__Daylin_.Models.DentistaViewModel", b =>
                {
                    b.Property<int>("idDentista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDDENTISTA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDentista"));

                    b.Property<string>("correoDentista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CORREODENTISTA");

                    b.Property<string>("nombreDentista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOMBREDENTISTA");

                    b.Property<string>("telefonoDentista")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("TELEFONODENTISTA");

                    b.HasKey("idDentista");

                    b.ToTable("Dentistas");
                });

            modelBuilder.Entity("ProyectoFinal_LP3__Daylin_.Models.MotivoViewModel", b =>
                {
                    b.Property<int>("idMotivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDMOTIVO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idMotivo"));

                    b.Property<string>("descripcionMotivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DESCRIPCIONMOTIVO");

                    b.HasKey("idMotivo");

                    b.ToTable("Motivos");
                });

            modelBuilder.Entity("ProyectoFinal_LP3__Daylin_.Models.PacienteViewModel", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaciente"));

                    b.Property<string>("cedulaPaciente")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("CEDULA");

                    b.Property<string>("nombrePaciente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOMBREPACIENTE");

                    b.Property<string>("telefonoPaciente")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("TELEFONOPACIENTE");

                    b.HasKey("IdPaciente");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("ProyectoFinal_LP3__Daylin_.Models.CitaViewModel", b =>
                {
                    b.HasOne("ProyectoFinal_LP3__Daylin_.Models.DentistaViewModel", "Dentista")
                        .WithMany()
                        .HasForeignKey("idDentista")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoFinal_LP3__Daylin_.Models.MotivoViewModel", "Motivo")
                        .WithMany()
                        .HasForeignKey("idMotivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoFinal_LP3__Daylin_.Models.PacienteViewModel", "Paciente")
                        .WithMany()
                        .HasForeignKey("idPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dentista");

                    b.Navigation("Motivo");

                    b.Navigation("Paciente");
                });
#pragma warning restore 612, 618
        }
    }
}
